"use client";

import { useEffect } from "react";

const STORAGE_KEY = "dentalflow-language";

const TRANSLATIONS: Record<string, Record<string, string>> = {
  es: {
    "sidebar.lang": "Idioma",
    "sidebar.panel": "Panel",
    "sidebar.patients": "Pacientes",
    "sidebar.appointments": "Citas",
    "sidebar.waitingRoom": "Sala de espera",
    "sidebar.accounts": "Cuentas",
    "demo.banner": "Versión de demostración · todos los datos son ficticios",
    "notifications.accessRequest": "Quiere entrar otra vez (visita):",
    "accounts.guestHours": "Tiempo de acceso de la visita",
    "accounts.guestHint": "Al cerrar sesión o al vencer el tiempo, su acceso se cierra solo. Si quiere volver, te llega un aviso.",
    "accounts.temporary": "Cuenta temporal (visita)",
    "accounts.grantAgain": "Dar acceso otra vez",
    "accounts.requests": "Visitas que quieren entrar otra vez",
    "accounts.requestsHint": "Para dejarla entrar, busca su cuenta abajo y toca «Dar acceso otra vez».",
    "accounts.guestUntil": "Cuenta temporal: acceso hasta",
    "accounts.guestExpired": "Cuenta temporal: el acceso ya venció.",
    "billing.title": "Facturación",
    "billing.patientLoadError": "No se pudo cargar la información del paciente.",
    "billing.balanceLoadError": "No se pudo calcular el balance porque faltan datos de cargos o pagos.",
    "billing.summary.charged": "Cargado al paciente",
    "billing.summary.paid": "Pagado",
    "billing.summary.credit": "Saldo a favor",
    "billing.summary.balance": "Balance",
    "billing.summary.arsPending": "Pendiente de la ARS",
    "billing.chargesLoadError": "No se pudieron cargar los cargos.",
    "billing.paymentsLoadError": "No se pudieron cargar los pagos.",
    "billing.planLoadError": "No se pudieron cargar los procedimientos completados.",
    "billing.newCharge": "Nuevo cargo",
    "billing.completedUnbilled": "Procedimientos completados sin cobrar",
    "billing.noCompletedUnbilled": "No hay procedimientos completados sin cobrar.",
    "billing.chargeProcedure": "Cobrar",
    "billing.description": "Descripción",
    "billing.amount": "Monto (RD$)",
    "billing.amountPlaceholder": "Ej.: 3,500",
    "billing.arsCoverage": "Cobertura de la ARS (opcional)",
    "billing.arsName": "ARS",
    "billing.arsAuthorization": "Autorización de la ARS (opcional)",
    "billing.saving": "Guardando…",
    "billing.chargeSaved": "Cargo guardado.",
    "billing.saveCharge": "Guardar cargo",
    "billing.newPayment": "Registrar pago",
    "billing.paymentMethod": "Forma de pago",
    "billing.paymentAmountPlaceholder": "Ej.: 1,500",
    "billing.reference": "Referencia",
    "billing.note": "Nota",
    "billing.receipt": "Recibo N.°",
    "billing.savePayment": "Registrar pago",
    "billing.method.efectivo": "Efectivo",
    "billing.method.tarjeta": "Tarjeta",
    "billing.method.transferencia": "Transferencia",
    "billing.method.cheque": "Cheque",
    "billing.charges": "Cargos",
    "billing.chargesEmpty": "No hay cargos registrados.",
    "billing.arsCoverageShort": "Cobertura ARS",
    "billing.patientAmount": "Paga el paciente",
    "billing.arsStatus.no_aplica": "Sin ARS",
    "billing.arsStatus.pendiente": "Pendiente de reclamar",
    "billing.arsStatus.reclamado": "Reclamado",
    "billing.arsStatus.pagado": "Pagado por la ARS",
    "billing.arsStatus.rechazado": "Rechazado por la ARS",
    "billing.created": "Registrado",
    "billing.unknownUser": "Usuario desconocido",
    "billing.voided": "Anulado",
    "billing.reason": "Motivo",
    "billing.voidCharge": "Anular cargo",
    "billing.voidPayment": "Anular pago",
    "billing.voidReason": "Motivo de la anulación",
    "billing.voidSaved": "Anulación registrada.",
    "billing.confirmVoid": "Confirmar anulación",
    "billing.advanceClaim": "Avanzar reclamo:",
    "billing.payments": "Pagos",
    "billing.paymentsEmpty": "No hay pagos registrados.",
    "billing.receivedBy": "Recibido por",
    "billing.error.permission": "Solo recepción y administración pueden registrar cobros.",
    "billing.error.description": "Escribe la descripción del cargo.",
    "billing.error.chargeAmount": "El monto no es válido. Ej.: 3,500",
    "billing.error.paymentAmount": "El monto no es válido. Ej.: 1,500",
    "billing.error.arsCoverage": "La cobertura de la ARS no es válida.",
    "billing.error.arsCoverageTooHigh": "La cobertura de la ARS no puede ser mayor que el monto.",
    "billing.error.arsRequired": "Indica la ARS que cubre el cargo.",
    "billing.error.arsTooLong": "El nombre o la autorización de la ARS son demasiado largos.",
    "billing.error.planItemAlreadyBilled": "Ese procedimiento del plan ya fue cobrado.",
    "billing.error.chargeSave": "No se pudo guardar el cargo. Inténtalo de nuevo.",
    "billing.error.paymentMethod": "Selecciona la forma de pago.",
    "billing.error.paymentFieldsTooLong": "La referencia o la nota son demasiado largas.",
    "billing.error.paymentSave": "No se pudo registrar el pago. Inténtalo de nuevo.",
    "billing.error.voidReasonShort": "Escribe el motivo de la anulación (mínimo 5 caracteres).",
    "billing.error.voidReasonLong": "El motivo admite hasta 500 caracteres.",
    "billing.error.chargeVoid": "No se pudo anular el cargo. Recarga la página e inténtalo de nuevo.",
    "billing.error.paymentVoid": "No se pudo anular el pago. Recarga la página e inténtalo de nuevo.",
    "billing.error.arsTransition": "Ese cambio de estado de la ARS no es válido.",
    "billing.error.arsUpdate": "No se pudo actualizar el reclamo. Recarga la página e inténtalo de nuevo.",
    "plan.title": "Plan de tratamiento",
    "plan.toOdontogram": "Registrar en el odontograma",
    "plan.toOdontogram.none": "No registrar",
    "plan.subtitle": "Nada se borra: un procedimiento se cancela con motivo.",
    "plan.loadError": "No se pudo cargar el plan de tratamiento. Recarga la página.",
    "plan.procedure": "Procedimiento",
    "plan.tooth": "Diente (opcional)",
    "plan.cost": "Costo estimado (RD$)",
    "plan.surfaces": "Superficies (opcional)",
    "plan.add": "Agregar al plan",
    "plan.start": "Iniciar",
    "plan.markDone": "Marcar completado",
    "plan.cancel": "Cancelar procedimiento",
    "plan.cancelConfirm": "Confirmar cancelación",
    "plan.totalPending": "Por realizar",
    "plan.totalDone": "Realizado",
    "plan.total": "Total del plan",
    "plan.new": "Agregar procedimiento",
    "plan.items": "Procedimientos",
    "plan.readOnly": "Solo el doctor puede modificar el plan de tratamiento.",
    "plan.empty": "Este paciente todavía no tiene plan de tratamiento.",
    "plan.addedOn": "Agregado el",
    "plan.doneOn": "completado el",
    "plan.reason": "Motivo:",
    "plan.status.pendiente": "Pendiente",
    "plan.status.en_proceso": "En proceso",
    "plan.status.completado": "Completado",
    "plan.status.cancelado": "Cancelado",
    "odontogram.title": "Odontograma",
    "odontogram.noFindings": "Sin hallazgos",
    "odontogram.subtitle": "Cada hallazgo queda firmado con fecha y hora. No se borra: un error se anula con motivo.",
    "odontogram.loadError": "No se pudo cargar el odontograma. Recarga la página.",
    "odontogram.hint": "Toca un diente para ver su historial.",
    "odontogram.showPrimary": "Mostrar dientes temporales",
    "odontogram.pickTooth": "Selecciona un diente en el odontograma.",
    "odontogram.tooth": "Diente",
    "odontogram.readOnly": "Solo el doctor puede registrar hallazgos.",
    "odontogram.history": "Historial del diente",
    "odontogram.noHistory": "Sin registros para este diente.",
    "odontogram.condition": "Condición",
    "odontogram.surfaces": "Superficies",
    "odontogram.note": "Nota (opcional)",
    "odontogram.save": "Registrar hallazgo",
    "odontogram.void": "Anular (registrado por error)",
    "odontogram.voidConfirm": "Confirmar anulación",
    "odontogram.voidedOn": "Anulado",
    "odontogram.cond.sano": "Sano",
    "odontogram.cond.caries": "Caries",
    "odontogram.cond.obturacion": "Obturación",
    "odontogram.cond.sellante": "Sellante",
    "odontogram.cond.corona": "Corona",
    "odontogram.cond.endodoncia": "Endodoncia",
    "odontogram.cond.fractura": "Fractura",
    "odontogram.cond.extraccion_indicada": "Extracción indicada",
    "odontogram.cond.ausente": "Ausente",
    "odontogram.cond.implante": "Implante",
    "odontogram.surface.M": "Mesial",
    "odontogram.surface.D": "Distal",
    "odontogram.surface.O": "Oclusal / incisal",
    "odontogram.surface.V": "Vestibular",
    "odontogram.surface.L": "Lingual / palatino",
    "sidebar.logout": "Cerrar sesión",
    "sidebar.tagline1": "Sonrisas",
    "sidebar.tagline2": "que inspiran",
    "sidebar.tagline3": "vidas mejores",
    "role.doctor": "Doctor",
    "role.recepcion": "Recepción",
    "role.enfermeria": "Enfermería",
    "role.admin": "Admin",
    "insurance.private": "Privado",
    "insurance.none": "Sin aseguradora",
    "patients.table.contact": "Contacto",
    "patients.recordShort": "N.°",
    "chart.recordNo": "Expediente N.°",
    "chart.documentId": "Cédula",
    "chart.years": "años",
    "chart.affiliate": "Afiliado",
    "chart.noInsurance": "Sin aseguradora registrada",
    "chart.medications": "Medicamentos:",
    "chart.updated": "Actualizado",
    "chart.by": "por",
    "alert.penicillin": "Alergia a penicilina / amoxicilina",
    "alert.anesthetic": "Alergia a anestésicos locales",
    "alert.nsaids": "Alergia a AINEs",
    "alert.latex": "Alergia al látex",
    "alert.anticoagulants": "Toma anticoagulantes / antiagregantes",
    "alert.bisphosphonates": "Toma bifosfonatos",
    "alert.diabetes": "Diabetes",
    "alert.hypertension": "Hipertensión",
    "alert.heart": "Cardiopatía",
    "alert.pregnant": "Embarazo",
    "clinical.kind.nota": "Nota de evolución",
    "clinical.kind.medicamento": "Medicamento administrado",
    "clinical.kind.procedimiento": "Procedimiento",
    "clinical.administered": "administrado",
    "clinical.onlyStaff": "Solo doctores y enfermería pueden escribir en el registro clínico.",
    "accounts.field.name": "Nombre completo",
    "accounts.field.email": "Correo",
    "accounts.field.password": "Contraseña temporal",
    "accounts.field.role": "Rol",
    "accounts.passwordRule": "Mínimo 10 caracteres, con minúsculas, mayúsculas, números y símbolos.",
    "accounts.select": "Selecciona…",
    "accounts.create": "Crear cuenta",
    "accounts.changeRole": "Cambiar rol",
    "accounts.deactivate": "Desactivar cuenta",
    "accounts.createdOn": "Creada el",
    "accounts.active": "Activa",
    "accounts.inactive": "Desactivada",
    "accounts.title": "Cuentas",
    "accounts.subtitle": "Crea cuentas para el personal, asigna su rol y desactívalas cuando dejen la clínica. Las cuentas no se borran.",
    "accounts.new": "Nueva cuenta",
    "accounts.loadError": "No se pudieron cargar las cuentas. Recarga la página.",
    "waitingRoom.title": "Sala de espera",
    "waitingRoom.empty": "No hay pacientes en sala de espera.",
    "waitingRoom.doctor": "Doctor",
    "waitingRoom.waitingMinutes": "minutos esperando",
    "waitingRoom.action.arrived": "Llegó",
    "waitingRoom.action.call": "Llamar",
    "waitingRoom.action.inCare": "En atención",
    "waitingRoom.action.attended": "Atendido",
    "waitingRoom.action.cancel": "Cancelar",
    "waitingRoom.status.waiting": "En espera",
    "waitingRoom.status.called": "Llamado",
    "waitingRoom.status.inCare": "En atención",
    "waitingRoom.status.attended": "Atendido",
    "waitingRoom.status.cancelled": "Cancelado",
    "waitingRoom.error.permission": "No tienes permiso para realizar esta acción.",
    "waitingRoom.error.empty": "No tienes pacientes esperando.",
    "waitingRoom.action.callNext": "Llamar siguiente",
    "waitingRoom.error.save": "No se pudo guardar el cambio. Recarga la página e inténtalo de nuevo.",
    "waitingRoom.error.load": "No se pudo cargar la sala de espera. Recarga la página.",
    "appointments.queueLoadError": "No se pudo verificar la sala de espera; se ocultaron los botones de llegada.",
    "notifications.title": "Notificaciones",
    "notifications.loading": "Cargando notificaciones…",
    "notifications.empty": "Sin notificaciones pendientes.",
    "notifications.error": "No se pudieron cargar las notificaciones.",
    "notifications.appointmentSoon": "Cita en los próximos 30 minutos:",
    "notifications.queueWaiting": "Paciente en sala de espera:",
    "notifications.appointmentUnconfirmed": "Cita sin confirmar:",
    "notifications.missingHistory": "Registrar historial médico de",
    "chart.back": "← Pacientes",
    "chart.newAppointment": "Nueva cita",
    "chart.editData": "Editar datos",
    "chart.noHistory": "Historial médico no registrado",
    "chart.noHistory.hint": "Pregunte por alergias, medicamentos y enfermedades antes de cualquier procedimiento, y regístrelo abajo.",
    "chart.alerts": "Alertas médicas",
    "chart.noAlerts": "Sin alertas médicas registradas",
    "chart.clinical": "Registro clínico",
    "chart.clinical.hint": "Notas de evolución, medicamentos administrados y procedimientos. Lo registrado no se edita ni se borra: se corrige con motivo.",
    "chart.history": "Historial médico",
    "chart.history.hint": "Marque lo que aplique. Quien guarde queda registrado con fecha y hora.",
    "chart.upcoming": "Próximas citas",
    "chart.past": "Citas anteriores",
    "chart.notes": "Notas",
    "medical.allergies": "Alergias",
    "medical.allergy.penicillin": "Penicilina / amoxicilina",
    "medical.allergy.anesthetic": "Anestésicos locales",
    "medical.allergy.nsaids": "AINEs (ibuprofeno, aspirina)",
    "medical.allergy.latex": "Látex",
    "medical.allergies.other": "Otras alergias",
    "medical.medications": "Medicamentos",
    "medical.med.anticoagulants": "Anticoagulantes / antiagregantes",
    "medical.med.bisphosphonates": "Bifosfonatos",
    "medical.medications.current": "Medicamentos actuales",
    "medical.conditions": "Condiciones",
    "medical.cond.diabetes": "Diabetes",
    "medical.cond.hypertension": "Hipertensión",
    "medical.cond.heart": "Cardiopatía",
    "medical.cond.pregnancy": "Embarazo",
    "medical.conditions.other": "Otras condiciones",
    "panel.title": "Panel general",
    "panel.welcome": "Hola, {name}",
    "panel.newAppointment": "+ nueva cita",
    "panel.loadError": "No se pudieron cargar algunos datos. Recarga la página.",
    "panel.kpi.patients": "Pacientes registrados",
    "panel.kpi.appointments": "Citas de hoy",
    "panel.kpi.waiting": "En sala de espera",
    "panel.kpi.completed": "Completadas hoy",
    "panel.agenda": "Agenda de Hoy",
    "panel.agenda.subtitle": "Citas programadas",
    "panel.agenda.view": "Ver todo",
    "panel.agenda.empty": "No hay citas para hoy.",
    "panel.recent": "Pacientes recientes",
    "panel.recent.view": "Ver todos",
    "panel.recent.empty": "Aún no hay pacientes registrados.",
    "panel.review.title": "Pacientes para revisión",
    "panel.review.lastVisit": "Última visita:",
    "panel.review.empty": "No hay pacientes pendientes de revisión.",
    "panel.review.loadError": "No se pudieron cargar los pacientes para revisión.",
    "appointments.title": "Citas",
    "appointments.new": "+ Nueva cita",
    "appointments.kpi.total": "Total del día",
    "appointments.kpi.pending": "Por confirmar",
    "appointments.kpi.confirmed": "Confirmadas",
    "appointments.empty": "No hay citas para este día.",
    "appointments.reasonMissing": "Sin motivo registrado",
    "appointments.patientFallback": "Paciente",
    "appointments.doctor": "Doctor",
    "appointments.change": "Cambiar",
    "appointments.status.current": "Estado actual:",
    "appointments.status.update": "Actualizar estado",
    "appointments.status.updating": "Actualizando…",
    "appointments.status.pending": "Pendiente",
    "appointments.status.unassigned": "Sin asignar",
    "appointments.form.title": "Nueva cita",
    "appointments.form.subtitle": "Programa una cita para un paciente.",
    "appointments.form.patient": "Paciente",
    "appointments.form.doctor": "Doctor",
    "appointments.form.selectDoctor": "Selecciona un doctor",
    "appointments.form.date": "Fecha",
    "appointments.form.time": "Hora",
    "appointments.form.duration": "Duración",
    "appointments.form.reason": "Motivo (opcional)",
    "appointments.form.reasonPlaceholder": "Limpieza, revisión, dolor…",
    "appointments.form.status": "Estado",
    "appointments.form.cancel": "Cancelar",
    "appointments.form.save": "Guardar cita",
    "appointments.form.saving": "Guardando…",
    "appointments.form.select": "Selecciona una opción",
    "patients.title": "Pacientes",
    "patients.subtitle": "Gestiona la lista de pacientes de la clínica.",
    "patients.new": "+ Nuevo paciente",
    "patients.search.placeholder": "Buscar por nombre o teléfono…",
    "patients.search.aria": "Buscar pacientes",
    "patients.table.record": "Expediente",
    "patients.table.name": "Nombre",
    "patients.table.document": "Cédula",
    "patients.table.phone": "Teléfono",
    "patients.table.insurance": "Aseguradora",
    "patients.table.registered": "Registrado",
    "patients.empty.search": "No se encontraron pacientes con ese criterio de búsqueda.",
    "patients.empty.none": "Todavía no hay pacientes registrados.",
    "patient.search.placeholder": "Buscar paciente por nombre, cédula o teléfono…",
    "patient.search.empty": "Sin resultados.",
    "patient.change": "Cambiar",
    "patient.unknown": "Paciente",
    "patient.form.fullName": "Nombre completo",
    "patient.form.fullNamePlaceholder": "Nombre y apellidos",
    "patient.form.documentLabel": "Cédula",
    "patient.form.documentRequired": "(obligatoria)",
    "patient.form.documentOptional": "(opcional)",
    "patient.form.phone": "Teléfono",
    "patient.form.email": "Correo (opcional)",
    "patient.form.emailPlaceholder": "paciente@correo.com",
    "patient.form.birthDate": "Fecha de nacimiento (opcional)",
    "patient.form.insurance": "Aseguradora",
    "patient.form.insuranceNone": "Sin especificar",
    "patient.form.ars": "ARS",
    "patient.form.private": "Privado",
    "patient.form.arsName": "Nombre de la ARS",
    "patient.form.affiliate": "Número de afiliado",
    "patient.form.notes": "Notas (opcional)",
    "patient.form.cancel": "Cancelar",
    "language.es": "Español",
    "language.en": "English",
  },
  en: {
    "sidebar.lang": "Language",
    "sidebar.panel": "Dashboard",
    "sidebar.patients": "Patients",
    "sidebar.appointments": "Appointments",
    "sidebar.waitingRoom": "Waiting room",
    "sidebar.accounts": "Accounts",
    "demo.banner": "Demo version · all data is fictional",
    "notifications.accessRequest": "Wants to come back in (visitor):",
    "accounts.guestHours": "Visitor access time",
    "accounts.guestHint": "Access closes automatically on sign-out or when time runs out. If they want to come back, you get a notification.",
    "accounts.temporary": "Temporary account (visitor)",
    "accounts.grantAgain": "Grant access again",
    "accounts.requests": "Visitors who want to come back in",
    "accounts.requestsHint": "To let them in, find their account below and tap «Grant access again».",
    "accounts.guestUntil": "Temporary account: access until",
    "accounts.guestExpired": "Temporary account: access has expired.",
    "billing.title": "Billing",
    "billing.patientLoadError": "Could not load the patient information.",
    "billing.balanceLoadError": "Could not calculate the balance because charges or payments are missing.",
    "billing.summary.charged": "Charged to patient",
    "billing.summary.paid": "Paid",
    "billing.summary.credit": "Credit balance",
    "billing.summary.balance": "Balance",
    "billing.summary.arsPending": "Pending from insurance",
    "billing.chargesLoadError": "Could not load charges.",
    "billing.paymentsLoadError": "Could not load payments.",
    "billing.planLoadError": "Could not load completed procedures.",
    "billing.newCharge": "New charge",
    "billing.completedUnbilled": "Completed procedures not yet billed",
    "billing.noCompletedUnbilled": "There are no completed procedures waiting to be billed.",
    "billing.chargeProcedure": "Bill",
    "billing.description": "Description",
    "billing.amount": "Amount (DOP)",
    "billing.amountPlaceholder": "E.g.: 3,500",
    "billing.arsCoverage": "Insurance coverage (optional)",
    "billing.arsName": "Insurance",
    "billing.arsAuthorization": "Insurance authorization (optional)",
    "billing.saving": "Saving…",
    "billing.chargeSaved": "Charge saved.",
    "billing.saveCharge": "Save charge",
    "billing.newPayment": "Record payment",
    "billing.paymentMethod": "Payment method",
    "billing.paymentAmountPlaceholder": "E.g.: 1,500",
    "billing.reference": "Reference",
    "billing.note": "Note",
    "billing.receipt": "Receipt No.",
    "billing.savePayment": "Record payment",
    "billing.method.efectivo": "Cash",
    "billing.method.tarjeta": "Card",
    "billing.method.transferencia": "Bank transfer",
    "billing.method.cheque": "Check",
    "billing.charges": "Charges",
    "billing.chargesEmpty": "No charges recorded.",
    "billing.arsCoverageShort": "Insurance coverage",
    "billing.patientAmount": "Patient pays",
    "billing.arsStatus.no_aplica": "No insurance",
    "billing.arsStatus.pendiente": "Pending submission",
    "billing.arsStatus.reclamado": "Submitted",
    "billing.arsStatus.pagado": "Paid by insurance",
    "billing.arsStatus.rechazado": "Rejected by insurance",
    "billing.created": "Recorded",
    "billing.unknownUser": "Unknown user",
    "billing.voided": "Voided",
    "billing.reason": "Reason",
    "billing.voidCharge": "Void charge",
    "billing.voidPayment": "Void payment",
    "billing.voidReason": "Reason for voiding",
    "billing.voidSaved": "Void recorded.",
    "billing.confirmVoid": "Confirm void",
    "billing.advanceClaim": "Advance claim:",
    "billing.payments": "Payments",
    "billing.paymentsEmpty": "No payments recorded.",
    "billing.receivedBy": "Received by",
    "billing.error.permission": "Only reception and administrators can register charges or payments.",
    "billing.error.description": "Enter a description for the charge.",
    "billing.error.chargeAmount": "The amount is invalid. Example: 3,500",
    "billing.error.paymentAmount": "The amount is invalid. Example: 1,500",
    "billing.error.arsCoverage": "The insurance coverage is invalid.",
    "billing.error.arsCoverageTooHigh": "Insurance coverage cannot exceed the amount.",
    "billing.error.arsRequired": "Select the insurance provider covering this charge.",
    "billing.error.arsTooLong": "The insurance provider or authorization is too long.",
    "billing.error.planItemAlreadyBilled": "This treatment plan procedure has already been billed.",
    "billing.error.chargeSave": "Could not save the charge. Try again.",
    "billing.error.paymentMethod": "Select a payment method.",
    "billing.error.paymentFieldsTooLong": "The reference or note is too long.",
    "billing.error.paymentSave": "Could not record the payment. Try again.",
    "billing.error.voidReasonShort": "Enter a reason for voiding (at least 5 characters).",
    "billing.error.voidReasonLong": "The reason can contain up to 500 characters.",
    "billing.error.chargeVoid": "Could not void the charge. Reload the page and try again.",
    "billing.error.paymentVoid": "Could not void the payment. Reload the page and try again.",
    "billing.error.arsTransition": "That insurance claim status change is not valid.",
    "billing.error.arsUpdate": "Could not update the claim. Reload the page and try again.",
    "plan.title": "Treatment plan",
    "plan.toOdontogram": "Record on dental chart",
    "plan.toOdontogram.none": "Don't record",
    "plan.subtitle": "Nothing is deleted: a procedure is cancelled with a reason.",
    "plan.loadError": "Could not load the treatment plan. Reload the page.",
    "plan.procedure": "Procedure",
    "plan.tooth": "Tooth (optional)",
    "plan.cost": "Estimated cost (RD$)",
    "plan.surfaces": "Surfaces (optional)",
    "plan.add": "Add to plan",
    "plan.start": "Start",
    "plan.markDone": "Mark as done",
    "plan.cancel": "Cancel procedure",
    "plan.cancelConfirm": "Confirm cancellation",
    "plan.totalPending": "To do",
    "plan.totalDone": "Done",
    "plan.total": "Plan total",
    "plan.new": "Add procedure",
    "plan.items": "Procedures",
    "plan.readOnly": "Only the doctor can change the treatment plan.",
    "plan.empty": "This patient has no treatment plan yet.",
    "plan.addedOn": "Added on",
    "plan.doneOn": "done on",
    "plan.reason": "Reason:",
    "plan.status.pendiente": "Pending",
    "plan.status.en_proceso": "In progress",
    "plan.status.completado": "Done",
    "plan.status.cancelado": "Cancelled",
    "odontogram.title": "Dental chart",
    "odontogram.noFindings": "No findings",
    "odontogram.subtitle": "Every finding is signed with date and time. Nothing is deleted: mistakes are voided with a reason.",
    "odontogram.loadError": "Could not load the dental chart. Reload the page.",
    "odontogram.hint": "Tap a tooth to see its history.",
    "odontogram.showPrimary": "Show primary teeth",
    "odontogram.pickTooth": "Select a tooth on the chart.",
    "odontogram.tooth": "Tooth",
    "odontogram.readOnly": "Only the doctor can record findings.",
    "odontogram.history": "Tooth history",
    "odontogram.noHistory": "No records for this tooth.",
    "odontogram.condition": "Condition",
    "odontogram.surfaces": "Surfaces",
    "odontogram.note": "Note (optional)",
    "odontogram.save": "Record finding",
    "odontogram.void": "Void (recorded by mistake)",
    "odontogram.voidConfirm": "Confirm void",
    "odontogram.voidedOn": "Voided",
    "odontogram.cond.sano": "Healthy",
    "odontogram.cond.caries": "Caries",
    "odontogram.cond.obturacion": "Filling",
    "odontogram.cond.sellante": "Sealant",
    "odontogram.cond.corona": "Crown",
    "odontogram.cond.endodoncia": "Root canal",
    "odontogram.cond.fractura": "Fracture",
    "odontogram.cond.extraccion_indicada": "Extraction needed",
    "odontogram.cond.ausente": "Missing",
    "odontogram.cond.implante": "Implant",
    "odontogram.surface.M": "Mesial",
    "odontogram.surface.D": "Distal",
    "odontogram.surface.O": "Occlusal / incisal",
    "odontogram.surface.V": "Buccal",
    "odontogram.surface.L": "Lingual / palatal",
    "sidebar.logout": "Sign out",
    "sidebar.tagline1": "Smiles",
    "sidebar.tagline2": "that inspire",
    "sidebar.tagline3": "better lives",
    "role.doctor": "Doctor",
    "role.recepcion": "Front desk",
    "role.enfermeria": "Nursing",
    "role.admin": "Admin",
    "insurance.private": "Private",
    "insurance.none": "No insurance",
    "patients.table.contact": "Contact",
    "patients.recordShort": "No.",
    "chart.recordNo": "Record No.",
    "chart.documentId": "ID",
    "chart.years": "years old",
    "chart.affiliate": "Member ID",
    "chart.noInsurance": "No insurance on file",
    "chart.medications": "Medications:",
    "chart.updated": "Updated",
    "chart.by": "by",
    "alert.penicillin": "Penicillin / amoxicillin allergy",
    "alert.anesthetic": "Local anesthetic allergy",
    "alert.nsaids": "NSAID allergy",
    "alert.latex": "Latex allergy",
    "alert.anticoagulants": "Takes anticoagulants / antiplatelets",
    "alert.bisphosphonates": "Takes bisphosphonates",
    "alert.diabetes": "Diabetes",
    "alert.hypertension": "Hypertension",
    "alert.heart": "Heart disease",
    "alert.pregnant": "Pregnancy",
    "clinical.kind.nota": "Progress note",
    "clinical.kind.medicamento": "Medication given",
    "clinical.kind.procedimiento": "Procedure",
    "clinical.administered": "given",
    "clinical.onlyStaff": "Only doctors and nursing staff can write in the clinical record.",
    "accounts.field.name": "Full name",
    "accounts.field.email": "Email",
    "accounts.field.password": "Temporary password",
    "accounts.field.role": "Role",
    "accounts.passwordRule": "At least 10 characters, with lowercase, uppercase, numbers and symbols.",
    "accounts.select": "Select…",
    "accounts.create": "Create account",
    "accounts.changeRole": "Change role",
    "accounts.deactivate": "Deactivate account",
    "accounts.createdOn": "Created on",
    "accounts.active": "Active",
    "accounts.inactive": "Deactivated",
    "accounts.title": "Accounts",
    "accounts.subtitle": "Create staff accounts, assign their role and deactivate them when they leave the clinic. Accounts are never deleted.",
    "accounts.new": "New account",
    "accounts.loadError": "Could not load accounts. Reload the page.",
    "waitingRoom.title": "Waiting room",
    "waitingRoom.empty": "There are no patients in the waiting room.",
    "waitingRoom.doctor": "Doctor",
    "waitingRoom.waitingMinutes": "minutes waiting",
    "waitingRoom.action.arrived": "Arrived",
    "waitingRoom.action.call": "Call",
    "waitingRoom.action.inCare": "In treatment",
    "waitingRoom.action.attended": "Attended",
    "waitingRoom.action.cancel": "Cancel",
    "waitingRoom.status.waiting": "Waiting",
    "waitingRoom.status.called": "Called",
    "waitingRoom.status.inCare": "In treatment",
    "waitingRoom.status.attended": "Attended",
    "waitingRoom.status.cancelled": "Cancelled",
    "waitingRoom.error.permission": "You do not have permission to perform this action.",
    "waitingRoom.error.empty": "You have no patients waiting.",
    "waitingRoom.action.callNext": "Call next",
    "waitingRoom.error.save": "Could not save the change. Reload the page and try again.",
    "waitingRoom.error.load": "Could not load the waiting room. Reload the page.",
    "appointments.queueLoadError": "Could not verify the waiting room; arrival buttons were hidden.",
    "notifications.title": "Notifications",
    "notifications.loading": "Loading notifications…",
    "notifications.empty": "No pending notifications.",
    "notifications.error": "Could not load notifications.",
    "notifications.appointmentSoon": "Appointment starting in the next 30 minutes:",
    "notifications.queueWaiting": "Patient in waiting room:",
    "notifications.appointmentUnconfirmed": "Unconfirmed appointment:",
    "notifications.missingHistory": "Record medical history for",
    "chart.back": "← Patients",
    "chart.newAppointment": "New appointment",
    "chart.editData": "Edit data",
    "chart.noHistory": "Medical history not recorded",
    "chart.noHistory.hint": "Ask about allergies, medications, and conditions before any procedure, and record them below.",
    "chart.alerts": "Medical alerts",
    "chart.noAlerts": "No medical alerts recorded",
    "chart.clinical": "Clinical record",
    "chart.clinical.hint": "Progress notes, medications administered, and procedures. Entries are not edited or deleted: they are corrected with a reason.",
    "chart.history": "Medical history",
    "chart.history.hint": "Check all that apply. The person saving the record is logged with date and time.",
    "chart.upcoming": "Upcoming appointments",
    "chart.past": "Previous appointments",
    "chart.notes": "Notes",
    "medical.allergies": "Allergies",
    "medical.allergy.penicillin": "Penicillin / amoxicillin",
    "medical.allergy.anesthetic": "Local anesthetics",
    "medical.allergy.nsaids": "NSAIDs (ibuprofen, aspirin)",
    "medical.allergy.latex": "Latex",
    "medical.allergies.other": "Other allergies",
    "medical.medications": "Medications",
    "medical.med.anticoagulants": "Anticoagulants / antiplatelet agents",
    "medical.med.bisphosphonates": "Bisphosphonates",
    "medical.medications.current": "Current medications",
    "medical.conditions": "Conditions",
    "medical.cond.diabetes": "Diabetes",
    "medical.cond.hypertension": "Hypertension",
    "medical.cond.heart": "Heart disease",
    "medical.cond.pregnancy": "Pregnancy",
    "medical.conditions.other": "Other conditions",
    "panel.title": "Overview",
    "panel.welcome": "Hello, {name}",
    "panel.newAppointment": "+ new appointment",
    "panel.loadError": "Some data could not be loaded. Reload the page.",
    "panel.kpi.patients": "Registered patients",
    "panel.kpi.appointments": "Appointments today",
    "panel.kpi.waiting": "In waiting room",
    "panel.kpi.completed": "Completed today",
    "panel.agenda": "Today’s Agenda",
    "panel.agenda.subtitle": "Scheduled appointments",
    "panel.agenda.view": "View all",
    "panel.agenda.empty": "No appointments today.",
    "panel.recent": "Recent patients",
    "panel.recent.view": "View all",
    "panel.recent.empty": "No patients registered yet.",
    "panel.review.title": "Patients for review",
    "panel.review.lastVisit": "Last visit:",
    "panel.review.empty": "No patients pending review.",
    "panel.review.loadError": "Could not load patients for review.",
    "appointments.title": "Appointments",
    "appointments.new": "+ New appointment",
    "appointments.kpi.total": "Total for the day",
    "appointments.kpi.pending": "To confirm",
    "appointments.kpi.confirmed": "Confirmed",
    "appointments.empty": "No appointments for this day.",
    "appointments.reasonMissing": "No reason recorded",
    "appointments.patientFallback": "Patient",
    "appointments.doctor": "Doctor",
    "appointments.change": "Change",
    "appointments.status.current": "Current status:",
    "appointments.status.update": "Update status",
    "appointments.status.updating": "Updating…",
    "appointments.status.pending": "Pending",
    "appointments.status.unassigned": "Unassigned",
    "appointments.form.title": "New appointment",
    "appointments.form.subtitle": "Schedule an appointment for a patient.",
    "appointments.form.patient": "Patient",
    "appointments.form.doctor": "Doctor",
    "appointments.form.selectDoctor": "Select a doctor",
    "appointments.form.date": "Date",
    "appointments.form.time": "Time",
    "appointments.form.duration": "Duration",
    "appointments.form.reason": "Reason (optional)",
    "appointments.form.reasonPlaceholder": "Cleaning, review, pain…",
    "appointments.form.status": "Status",
    "appointments.form.cancel": "Cancel",
    "appointments.form.save": "Save appointment",
    "appointments.form.saving": "Saving…",
    "appointments.form.select": "Select an option",
    "patients.title": "Patients",
    "patients.subtitle": "Manage the clinic patient list.",
    "patients.new": "+ New patient",
    "patients.search.placeholder": "Search by name or phone…",
    "patients.search.aria": "Search patients",
    "patients.table.record": "Record",
    "patients.table.name": "Name",
    "patients.table.document": "ID",
    "patients.table.phone": "Phone",
    "patients.table.insurance": "Insurance",
    "patients.table.registered": "Registered",
    "patients.empty.search": "No patients matched that search.",
    "patients.empty.none": "No patients registered yet.",
    "patient.search.placeholder": "Search patient by name, ID or phone…",
    "patient.search.empty": "No results.",
    "patient.change": "Change",
    "patient.unknown": "Patient",
    "patient.form.fullName": "Full name",
    "patient.form.fullNamePlaceholder": "Name and surname",
    "patient.form.documentLabel": "Document",
    "patient.form.documentRequired": "(required)",
    "patient.form.documentOptional": "(optional)",
    "patient.form.phone": "Phone",
    "patient.form.email": "Email (optional)",
    "patient.form.emailPlaceholder": "patient@email.com",
    "patient.form.birthDate": "Birth date (optional)",
    "patient.form.insurance": "Insurance",
    "patient.form.insuranceNone": "Not specified",
    "patient.form.ars": "Health insurance",
    "patient.form.private": "Private",
    "patient.form.arsName": "Insurance provider",
    "patient.form.affiliate": "Affiliate number",
    "patient.form.notes": "Notes (optional)",
    "patient.form.cancel": "Cancel",
    "language.es": "Spanish",
    "language.en": "English",
  },
};

function applyTranslations(lang: string) {
  const dictionary = TRANSLATIONS[lang] ?? TRANSLATIONS.es;

  document.documentElement.lang = lang;

  const nodes = document.querySelectorAll<HTMLElement>("[data-i18n]");

  nodes.forEach((node) => {
    const key = node.dataset.i18n;
    if (!key) return;

    const value = dictionary[key];
    if (!value) return;

    setOwnText(node, value);
  });

  const placeholderNodes = document.querySelectorAll<HTMLInputElement | HTMLTextAreaElement>("[data-i18n-placeholder]");
  placeholderNodes.forEach((node) => {
    const key = node.dataset.i18nPlaceholder;
    if (!key) return;

    const value = dictionary[key];
    if (!value) return;

    node.placeholder = value;
  });

  // Fechas ("jueves, 1 de octubre"): data-i18n-date lleva el día (AAAA-MM-DD).
  const dateNodes = document.querySelectorAll<HTMLElement>("[data-i18n-date]");
  dateNodes.forEach((node) => {
    const dateKey = node.dataset.i18nDate;
    if (!dateKey || !/^\d{4}-\d{2}-\d{2}$/.test(dateKey)) return;
    const formatted = new Intl.DateTimeFormat(lang === "en" ? "en-US" : "es-DO", {
      timeZone: "UTC",
      weekday: "long",
      day: "numeric",
      month: "long",
    }).format(new Date(`${dateKey}T12:00:00Z`));
    const text = formatted.charAt(0).toUpperCase() + formatted.slice(1);
    if (node.textContent !== text) node.textContent = text;
  });

  const nameNodes = document.querySelectorAll<HTMLElement>("[data-i18n-name]");
  nameNodes.forEach((node) => {
    const key = node.dataset.i18nName;
    if (!key) return;

    const template = dictionary[key];
    if (!template) return;

    const userName = node.dataset.userName ?? "";
    setOwnText(node, template.replace("{name}", userName));
  });
}

// Cambia solo el texto propio del elemento, sin tocar sus hijos (inputs,
// selects) y reutilizando el nodo de texto existente para no romper a React.
function setOwnText(node: HTMLElement, value: string) {
  const textNodes = Array.from(node.childNodes).filter(
    (child): child is Text => child.nodeType === Node.TEXT_NODE
  );
  const target = textNodes.find((child) => child.data.trim() !== "") ?? textNodes[0];

  if (!target) {
    if (node.childElementCount === 0) node.textContent = value;
    return;
  }

  const next = node.childElementCount === 0 ? value : `${value} `;
  if (target.data !== next) target.data = next;
  if (node.childElementCount === 0) {
    textNodes.forEach((child) => {
      if (child !== target) child.data = "";
    });
  }
}

export function LanguageBridge() {
  useEffect(() => {
    const getStoredLanguage = () => {
      if (typeof window === "undefined") return "es";
      const stored = localStorage.getItem(STORAGE_KEY);
      return stored && stored in TRANSLATIONS ? stored : "es";
    };

    const handleLanguageChange = (event: Event) => {
      const customEvent = event as CustomEvent<string>;
      const lang = customEvent.detail ?? getStoredLanguage();
      localStorage.setItem(STORAGE_KEY, lang);
      applyTranslations(lang);
    };

    const initialLanguage = getStoredLanguage();
    document.documentElement.lang = initialLanguage;
    localStorage.setItem(STORAGE_KEY, initialLanguage);
    applyTranslations(initialLanguage);

    document.addEventListener("dentalflow-language-change", handleLanguageChange);

    // El contenido de cada pantalla llega después (streaming, navegación,
    // recargas de datos): se vuelve a traducir cuando cambia el DOM.
    let frame = 0;
    const observer = new MutationObserver(() => {
      if (frame) return;
      frame = requestAnimationFrame(() => {
        frame = 0;
        const lang = getStoredLanguage();
        if (lang !== "es") applyTranslations(lang);
      });
    });
    observer.observe(document.body, { childList: true, subtree: true });

    return () => {
      document.removeEventListener("dentalflow-language-change", handleLanguageChange);
      observer.disconnect();
      if (frame) cancelAnimationFrame(frame);
    };
  }, []);

  return null;
}
